---

# Task 1: Familiarize Yourself with the Dataset

There are two main subtasks:  
1. Load the four data files that are part of this dataset.  
2. Explore each dataset and define the data types of each column. Describe the contents of each column, including the nature of the data values. Follow a similar approach as demonstrated in the lecture and tutorial. Discuss the shape of the data, value ranges, and possible categories. Convert any data into a more appropriate format if needed.  

Add as many code and markdown cells as necessary below. Typically, you should perform one type of investigation per code cell with output, and then comment on the results in a markdown cell below it.  

After completing the analysis, write a concise summary in the **Task 1: summary report** cell at the end. The final report should succinctly summarize the main characteristics of each data file, how they relate to each other, and any notable features.

In [24]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### Loading the Four Data Files

In [25]:
# Load each .csv into a dataframe
df_sessions = pd.read_csv("data/sessions.csv")
df_streamers = pd.read_csv("data/streamers.csv")
df_streams = pd.read_csv("data/streams.csv")
df_viewers = pd.read_csv("data/viewers.csv")

### sessions.csv

*Columns*

- *session_id*: **Numerical**
    - the id of the session a viewer watches a stream (the id starts with SES) (string)
- *viewer_id*: **Numerical**
    - the id of the viewer (the id starts with VWR) (string)
- *streamer_id*: **Numerical**
    - the id of the streamer (the id starts with STR) (string)
- *stream_id*: **Numerical**
    - the id of the stream (the id starts with SM) (string)
- *started_at*: **Numerical**
    - the date and time the viewer started watching (year-month-date hour:min:sec format) (string)
- *ended_at*: **Numerical**
    - the date and time the viewer stopped watching (year-month-date hour:min:sec format) (string)
- *duration_mins*: **Numerical**
    - how long and sessions lastes in minutes (integer)
- *chat_messanges_sent*: **Numerical**
    - number of chat messages sent during the session (integer)
- *bits_cheered*: **Numerical**
    - number of bits cheered during the session (integer)
- *followed_during*: **Categorical**
    - did the viewer follow the streamer during the session (boolean)
- *subscribed_during*: **Categorical**
    - did the viewer subscribe to the streamer during the session (boolean)

In [26]:
df_sessions.head()

,session_id,viewer_id,streamer_id,stream_id,started_at,ended_at,duration_mins,chat_messages_sent,bits_cheered,followed_during,subscribed_during
0,SES000001,VWR00938,STR0055,SM00860,2024-01-18 19:16:00,2024-01-18 20:28:00,72,0,0,False,False
1,SES000002,VWR00804,STR0034,SM00542,2024-01-04 17:11:00,2024-01-04 19:41:00,150,11,0,False,False
2,SES000003,VWR00704,STR0008,SM00124,2024-02-15 15:11:00,2024-02-15 16:53:00,102,5,0,False,False
3,SES000004,VWR00926,STR0024,SM00373,2024-01-18 19:59:00,2024-01-18 20:56:00,57,3,9663,False,False
4,SES000005,VWR00883,STR0008,SM00120,2024-03-19 20:08:00,2024-03-19 20:22:00,14,7,0,False,False

#### Value Ranges

In [46]:
print(
    "Value Range of duration_mins: " +
    str(df_sessions["duration_mins"].min()) +
    "-"  + str(df_sessions["duration_mins"].max())
)

print(
    "Value Range of chat_messages_sent: " +
    str(df_sessions["chat_messages_sent"].min()) +
    "-"  + str(df_sessions["chat_messages_sent"].max())
)

print(
    "Value Range of bits_cheered: " +
    str(df_sessions["bits_cheered"].min()) +
    "-"  + str(df_sessions["bits_cheered"].max())
)

Value Range of duration_mins: 0-443
Value Range of chat_messages_sent: 0-1987
Value Range of bits_cheered: 0-10000

### streamers.csv

*Columns*

- *streamer_id*: **Numerical**
    - the id of the streamer (the id starts with STR) (string)
- *streamer_name*: **Unstructured**
    - the name of the streamer (string)
- *category*: **Categorical**
    - the type of streams the streamer does (string)
- *language*: **Categorical**
    - the language used during the streams (string)
- *partner_status*: **Categorical**
    - does the streamer have a partner (boolean)
- *total_followers*: **Numerical**
    - the total amount of followers the streamer has (integer)
- *avg_concurrent_viewers*: **Numerical**
    - average concurrent viewers per stream (integer)

In [27]:
df_streamers.head()

,streamer_id,streamer_name,category,language,partner_status,total_followers,avg_concurrent_viewers
0,STR0001,xQc,Just Chatting,English,True,11500000,138706
1,STR0002,Pokimane,Just Chatting,English,True,-25551,71660
2,STR0003,HasanAbi,Just Chatting,English,True,2600000,34220
3,STR0004,Amouranth,Just Chatting,English,True,6200000,68607
4,STR0005,Mizkif,Just Chatting,English,True,2100000,6771

#### Value Ranges

In [48]:
print(
    "Value Range of total_followers: " +
    str(df_streamers["total_followers"].min()) +
    "-"  + str(df_streamers["total_followers"].max())
)

print(
    "Value Range of avg_concurrent_viewers: " +
    str(df_streamers["avg_concurrent_viewers"].min()) +
    "-"  + str(df_streamers["avg_concurrent_viewers"].max())
)

Value Range of total_followers: -46964-18700000
Value Range of avg_concurrent_viewers: 634-156401

### streams.csv

*Columns*

- *stream_id*: **Numerical**
    - the id of the stream (the id starts with SM) (string)
- *streamer_id*: **Numerical**
    - the id of the streamer (the id starts with STR) (string)
- *started_at*: **Numerical**
    - the date and time the stream started (year-month-date hour:min:sec format) (string)
- *ended_at*: **Numerical**
    - the date and time the stream ended (year-month-date hour:min:sec format) (string)
- *stream_duration_hrs*: **Numerical**
    - how long the stream lasted in hours (float)
- *category*: **Categorical**
    - the type of stream (string)
- *peak_viewers*: **Numerical**
    - the highest viewer count during the stream (float)
- *title_has_hype_word*: **Categorical**
    - if the title of the stream has the word hype (boolean)
- *was_raid*: **Categorical**
    - of the stream was raided (boolean)

In [28]:
df_streams.head()

,stream_id,streamer_id,started_at,ended_at,stream_duration_hrs,category,peak_viewers,title_has_hype_word,was_raid
0,SM00001,STR0001,2024-02-14 18:00:00,2024-02-14 21:00:00,3.0,Just Chatting,108989.0,False,True
1,SM00002,STR0001,2024-01-28 18:00:00,2024-01-28 21:00:00,3.0,Just Chatting,51635.0,True,False
2,SM00003,STR0001,2024-01-31 09:00:00,2024-01-31 16:00:00,7.0,Just Chatting,212127.0,False,False
3,SM00004,STR0001,2024-03-03 14:00:00,2024-03-03 21:00:00,7.0,Just Chatting,186745.0,False,True
4,SM00005,STR0001,2024-01-24 18:00:00,2024-01-24 21:00:00,3.0,Just Chatting,87723.0,False,True

#### Value Ranges

In [49]:
print(
    "Value Range of stream_duration_hrs: " +
    str(df_streams["stream_duration_hrs"].min()) +
    "-"  + str(df_streams["stream_duration_hrs"].max())
)

print(
    "Value Range of peak_viewers: " +
    str(df_streams["peak_viewers"].min()) +
    "-"  + str(df_streams["peak_viewers"].max())
)

Value Range of stream_duration_hrs: 1.5-96.0
Value Range of peak_viewers: -50.0-370165.0

### viewers.csv

*Columns*

- *viewer_id*: **Numerical**
    - the id of the viewer (the id starts with VWR) (string)
- *age_group*: **Categorical**
    - the age range of the viewer (string)
- *country*: **Categorical**
    - the country the viewer are located in (string)
- *account_age_days*: **Numerical**
    - how on the viewer account is in days (int)
- *subscription_tier*: **Categorical**
    - the subscription tier of the viewer (string)
- *preferred_category*: **Categorical**
    - the type of stream the viewer prefers (string)

In [29]:
df_viewers.head()

,viewer_id,age_group,country,account_age_days,subscription_tier,preferred_category
0,VWR00001,18-24,AR,355,free,IRL
1,VWR00002,25-34,CA,1670,free,Creative
2,VWR00003,35-44,US,1108,free,Just Chatting
3,VWR00004,45+,NaN,822,tier1,FPS
4,VWR00005,25-34,DE,2226,free,Just Chatting

#### Value Ranges

In [50]:
print(
    "Value Range of account_age_days: " +
    str(df_viewers["account_age_days"].min()) +
    "-"  + str(df_viewers["account_age_days"].max())
)

Value Range of account_age_days: 33-3645

### Task 1 Summary Report

Write your report here, summarizing the work done in the cells above.

# Task 2: Data Cleaning, Diagnostics, and Corrections

Identify and resolve issues in the dataset. These can be of different kinds, such as:
- Look for duplicates or implausible values (e.g., users with negative followers, invalid age groups). Thoroughly document your exploration of the data. Decide whether these are outliers or the result of a systemic problem. If the latter, resolve the problem here; if they are outliers, we will address those later.  
- Define at least three heuristics (common-sense rules) to flag unusual entries (e.g., someone watching dozens of streams per day). Discuss whether what you found are errors or artifacts.  

I will repeat the instructions here, but this is expected for each task: each code cell should focus on a specific analysis. You should run the code, and in the markdown below each code cell and its result, provide a detailed interpretation of what you have uncovered in that step. After completing the analyses, summarize the key findings in the indicated summary report cell below.

In [30]:
# start code for Task 2 here

### Task 2 summary report

# Task 3: Descriptive Statistics and Visualizations

- Create summary statistics and visualizations to understand user characteristics  
- Create summary statistics for streams data overall, and summaries by age group, account tire, or peak viewers  
- Visualize the distribution of streams durations, popular categories,   
- Show category-specific information and compare streamers based on categories

In [31]:
#start code for Task 3 here

### Task 3 Summary report
summarize your findings here.

# Task 4: Dealing with Outliers and Missing Values

- Are there any missing values or outliers in the original data? Perform the analysis and report your findings.  
- Are there any outliers or missing values in the derived data? Perform the analysis and report your findings.  
- If there are no outliers or missing values, introduce 3–5% of missing values in a selected column and 1–2% of outliers in another column.  
- Experiment with two strategies for imputing missing values and two strategies for handling outliers. Show how each strategy affects the characteristics of the data.

In [32]:
#start code for Task 4 here

### Task 4 Summary report

# Task 5: Correlation and Behavioral Patterns

- Compute pairwise correlations between user features and the number of check-ins  
- Visualize the results using a correlation matrix (use a coolwarm color scheme and proper scaling)  
- Try Spearman rank correlation and explain when it is more appropriate than Pearson

In [33]:
# tast 5 code starts here

### Task 5 Summary report

# Task 6: Compare Behavior Across User Segments

- Segment users into 2–3 groups (e.g., by age bracket, account tire)  
- Compare their viewing behavior over time using boxplots or dot plots  
- Identify any outliers in group behavior and investigate them

In [34]:
# task 6 code start here

### Task 6 Summary report

# Task 7: Your Own EDA Questions

Formulate and explore two hypotheses of your own:  
- Propose questions based on curiosity (e.g., “Does a user's variety of categories influence morning vs. evening or session duration?”)  
- Use summary statistics and visualizations to answer each question  
- Briefly discuss what additional data would help you answer the questions more effectively

In [35]:
# task 7 code start here

### Task 7 Summary report

# Task 8: EDA Presentation (Insight Report)

Summarize your findings in a polished format:  
- Create 3–4 slides or a single-page report highlighting your most important insights  
- Include at least 2 charts and interpret them using clear, plain language  
- Apply Tufte’s principles: minimize chartjunk, maximize data-to-ink ratio, and ensure clear labeling